# Generated by Django 4.0.4 on 2022-05-26 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_alter_editor_options_editor_phone_number_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={'ordering': ['first_name']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='tag',
            new_name='tags',
        ),
    ]
