# Generated by Django 4.0.4 on 2022-06-03 10:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0007_alter_article_article_image_alter_article_editor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
